# -*- coding: utf-8 -*-
"""Distance Calculator based on coordinates using Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GiYXGNI9j9iT6Y_seOO_F4jghOmjjJZ3
"""

import pandas as pd
import numpy as np
import plotly.express as px

data  = pd.read_csv('deliverytime.txt')

print(data.head())

data.info()

data.isnull().sum()

R = 6371

def deg_to_rad(degrees):
  return degrees*(np.pi/180)

def dist(lat1,lon1,lat2,lon2):
  d_lat = deg_to_rad(lat2-lat1)
  d_long = deg_to_rad(lon2-lon1)
  a = np.sin(d_lat/2)**2 + np.cos(deg_to_rad(lat1)) * np.cos(deg_to_rad(lat2))*np.sin(d_long/2)**2
  c = 2*np.arctan2(np.sqrt(a),np.sqrt(1-a))
  return R*c

data['distance'] = np.nan

for i in range(len(data)):
  data.loc[i,'distance'] = dist(data.loc[i,'Restaurant_latitude'],
                                data.loc[i,'Restaurant_longitude'],
                                data.loc[i,'Delivery_location_latitude'],
                                data.loc[i, 'Delivery_location_longitude'])

print(data.head())